on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    
    steps:
      
    - name: connect and pull
      run:  cd /home/shubham/image-to-text && sudo git checkout . && sudo git pull origin master

    - name: restart server and other tasks
      run: cd /home/shubham/image-to-text && sudo sh entrypoint.sh
   
