on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    
    steps:
      
    - name: connect and pull
      run:  cd /home/shubham/image-to-text && sh entrypoint.sh
   
